[workspace]
resolver = "3"
members = ["./crates/error", "./crates/tao", "./crates/tao_tui"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
axum = "0.8.9"
chrono = "0.4.44"
clap = "4.6.1"
crossterm = "0.29.0"
env_logger = "0.11.10"
log = "0.4.29"
mime_guess = "2.0.5"
ratatui = "0.30.0"
rust-embed = "8.11.0"
rstest = "0.26.1"
serde = "1.0.228"
serde_json = "1.0.149"
sqlx = "0.8.6"
tokio = "1.49.0"
tower-http = "0.6.8"
uuid = "1.23.1"

[profile.dev]
incremental = true
