POST http://localhost:6969/api/project/fa6b9cb1-0ab0-44d1-8500-3aa080da22ed/report HTTP/1.1
Content-Type: application/json

{
	"project_id": "fa6b9cb1-0ab0-44d1-8500-3aa080da22ed",
	"reported_at": "2000-01-01T00:00:00Z",
	"release": "0.1.0",
	"body": "oh-my-fucking-god",
	"stack_trace": "here_then_there:then_there:again_there:69:420",
	"kind": "ERROR",
	"memory_usage": 12,
	"cpu_percent": 45.02,
	"disk_usage_percent": 23.054
}

###

GET http://localhost:6969/api/project/fa6b9cb1-0ab0-44d1-8500-3aa080da22ed/report HTTP/1.1

###

POST http://localhost:6969/api/project HTTP/1.1
Content-Type: application/json

{
	"name": "Some Other Project",
	"slug": "some-other-project-but-different"
}


###

GET http://localhost:6969/api/project HTTP/1.1
