[package]
name = "tao"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
axum = { workspace = true, features = ["macros"] }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
error = { path = "../error", features = ["axum", "sqlx", "tokio"] }
log = { workspace = true }
mime_guess = { workspace = true }
rstest = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true, features = [
  "runtime-tokio",
  "postgres",
  "macros",
  "migrate",
  "chrono",
  "uuid",
] }
tokio = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["cors"] }
uuid = { workspace = true, features = ["v4", "serde"] }

[build-dependencies]
vergen-git2 = { workspace = true }
