[package]
name = "tao_tracing"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["serde"] }
reqwest = { workspace = true, features = ["json"] }
sysinfo = { workspace = true }
tao_schema = { path = "../schema" }
tokio = { workspace = true, features = [] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
